### ISSUE TITLE
error upon "meteor add"

### ISSUE THREAD

**Issue by punund** [denysonique/Meteor-jade-handlebars#1]
Meteor 0.4.1:

```
> meteor add jade-handlebars

module.js:340
    throw err;
          ^
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at /usr/local/meteor/packages/jade-handlebars/package.js:8:12
    at _.extend.init_from_library (/usr/local/meteor/app/lib/packages.js:107:5)
    at Object.module.exports.get (/usr/local/meteor/app/lib/packages.js:225:11)
    at module.exports.list (/usr/local/meteor/app/lib/packages.js:277:32)
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/meteor/app/lib/third/underscore.js:76:11)
```

**Comment by ramstein74** [comment]
i got the same error.
Please help

Also i notice i have a folder jade inside meteor packages folder...

**Comment by ghost** [comment]
+1 I have the same issue

**Comment by NakedMoleRatScientist** [comment]
+1 same here.
